<template>
    <div class="py-4">
        <div class="flex flex-row my-5 px-4">
           <Link :href="$url+'/user/balance'" as="button">
                <div class="p-2 pl-0 mr-2">
                    <img :src="$asset+'/image/ui/BackArrow.svg'">
                </div>
            </Link>
            <div class="font-bold text-xl self-center text-white">
                Transfer to Wallet
            </div>
        </div>
        <div class="px-4 mb-8">
            <div class="text-white text-xs">Balance: (Gold Coins)</div>
            <div class="text-2xl text_c2 font-black">{{balance}} Ks</div>
        </div>
        <div class="px-4">
            <div class="before:rounded-xl border_grad2 mt-2 mb-5">
                <input v-model="amount" type="text" placeholder="Enter the transfer amount" class="py-7 w-full bg-transparent focus:outline-none text-center text-4xl font-bold text-white placeholder:text-lg">
            </div>
            <div class="px-5 text-white text-sm py-5">
                Here are the instructions for transferring balances to wallet:
                <div class="">
                    <div class="text-sm text-gray-500 my-3">1.  Gold coins generated by recycling box products can be used for cash with drawl.</div>
                    <div class="text-sm text-gray-500 my-3">2.  The recharge amount cannot be directly used for withdrawal</div>
                </div>
            </div>
        </div>
        <div class="absolute w-full bottom-10 px-4">
            <div class="py-3 btn_gradient rounded-full w-full text-white text-center" @click="submit()">Submit</div>
        </div>
        <success-modal v-model="success" :modalAmount="amount" :index="1"></success-modal>
        <validate-alert v-model="errorModal" :errors="errors"></validate-alert>
    </div>
</template>

<script>

import {Link} from '@inertiajs/inertia-vue'
import axios from 'axios'
import successModal from './modals/Success.vue'

export default {
    components: {
        Link,
        successModal
    },
    props: {
        balance: ''
    },
    data() {
        return {
            amount: '',
            success: false,
            errors: {},
            errorModal: false
        }
    },
    methods: {
        submit() {
            axios.post('/user/go-to-wallet', {
                amount: this.amount
            }).then(res => {
                this.success = true
            }).catch(error => {
                console.log(error)
                if(error.response.data.errors) {
                    this.errors = error.response.data.errors
                }
                else {
                    let message = []
                    message.push(error.response.data.message)
                    this.errors['message'] = message
                }
                this.errorModal = true
            })
        }
    }
}
</script>